import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import { AppContext } from "@/common/context/appContext";
import { Header } from "@/common/components/layout/header/header";
import Footer from "@/common/components/layout/footer/footer";
import AllModals from "@/common/modals/allModals/allModals";
import ToastProvider from "@/common/context/toastProvider";
import "@/common/assets/styles/global.scss";

const robotFlex = Roboto_Flex({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pixelate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotFlex.className}>
        <AppContext>
          <AllModals />
          <ToastProvider />
          <Header className="" />
          {children}
          <Footer className="" />
        </AppContext>
      </body>
    </html>
  );
}
