import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import { Header } from "@/common/components/layout/header/header";
import "../styles/global.scss";
import Footer from "@/common/components/layout/footer/footer";

const robotFlex = Roboto_Flex({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pixelate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotFlex.className}>
        <Header />
        {children}
        <Footer className="" />
      </body>
    </html>
  );
}
